llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  googleai:
    provider: "googleai"
    model_name: "gemini-2.5-flash"

